version: "3"
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: nest_prod
    container_name: nest_prod
    ports:
      - 3000:3000
    restart: unless-stopped

  db:
    image: mariadb:10
    container_name: nest-db
    environment:
      MYSQL_DATABASE: nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:
