version: "3"
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest
    container_name: nest
    ports:
      - 3000:3000
    command: sh -c "yarn db:upgrade && yarn start:dev"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_eight
    ports:
      - 3306:3306
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8",
        "--collation-server=utf8_general_ci",
      ]
    volumes:
      - mysqldata:/var/lib/mysql
      - .docker/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

volumes:
  mysqldata:
