name: Build & Test

on:
  pull_request:
    types: [opened]
  push:
env:
  APP_ENV: test
  JWT_SECRET_KEY: test

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build(Compile Typescript)
        working-directory: .
        run: npm run build
      - name: Run Unit Tests
        run: npm test
      - name: Run Basic e2e Tests
        run: npm run test:e2e
